#mac:
#	g++ Lab0.cpp GLSL_helper.cpp MStackHelp.cpp -DGL_GLEXT_PROTOTYPES -framework OpenGL -framework GLUT
all:
	g++ texture_release.cpp GLSL_helper.cpp -DGL_GLEXT_PROTOTYPES -lGL -lGLU -lglut
run:all
	./a.out