#mac:
#	g++ Lab0.cpp GLSL_helper.cpp MStackHelp.cpp -DGL_GLEXT_PROTOTYPES -framework OpenGL -framework GLUT
all:
	g++ Lab0.cpp GLSL_helper.cpp MStackHelp.cpp -DGL_GLEXT_PROTOTYPES -lGL -lGLU -lglut

run:
	make all
	./a.out
