#mac:
#	g++ Lab0.cpp GLSL_helper.cpp MStackHelp.cpp -DGL_GLEXT_PROTOTYPES -framework OpenGL -framework GLUT
linux:
	g++ Lab0.cpp GLSL_helper.cpp MStackHelp.cpp -DGL_GLEXT_PROTOTYPES -lGL -lGLU -lglut
	./a.out
tar:
	tar -cf mhenry02.tar *.cpp *.h Makefile README glm *.glsl